blogproject/blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'

urlpatterns = [
    path('' , views.IndexView.as_view(), name='index'),
    path('blog-detail/<int:pk>/', views.BlogDetailView.as_view(), name='blog_detail'),
        # scienceカテゴリの一覧ページのURLパターン
    path(
        # scienceカテゴリの一覧ページのURLは「science-list/」
        'science-list/',
        # viewsモジュールのBlogDetailを実行
        views.ScienceView.as_view(),
        # URLパターンの名前を'science_list'にする
        name='science_list'
        ),
    # dailylifeカテゴリの一覧ページのURLパターン
    path(
        # dailylifeカテゴリの一覧ページのURLは「dailylife-list/」
        'dailylife-list/',
        # viewsモジュールのDailylifeViewを実行
        views.DailylifeView.as_view(),
        # URLパターンの名前を'dailylife_list'にする
        name='dailylife_list'
        ),
    # musicカテゴリの一覧ページのURLパターン
    path(
        # scienceカテゴリの一覧ページのURLは「music-list/」
        'music-list/',
        # viewsモジュールのMusicViewを実行
        views.MusicView.as_view(),
        # URLパターンの名前を'music_list'にする
        name='music_list'
        ),
        
    # 問い合わせページのURLパターン
    path(
        # 問い合わせページのURLは「contact/」
        'contact/',
        # viewsモジュールのContactViewを実行,
        views.ContactView.as_view(),
        # URLパターンの名前を'contact'にする
        name='contact'
    ),
]

blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path, include # , include追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include(('blogapp.urls', 'blogapp'), namespace='blogapp')),
    path('mondai1/', include('mondai1.urls')),
    path('mondai1_2/', include('mondai1_2.urls')),
    path('mondai1_3/', include('mondai1_3.urls')),
    path('mondai2/', include('mondai2.urls')),
    path('seisaku/', include(('seisaku.urls', 'seisaku'), namespace='seisaku')),  # 制作課題 
]

blogproject/mondai1_3/urls.py
from django.urls import path
from . import views

app_name = 'mondai1_3'
urlpatterns = [
    path('', views.TopView.as_view(), name="top"),
    path('question/', views.QuestionView.as_view(), name='question'),
]


blogproject/test1_project/test1_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test1/',include('test1_app.urls')),
]

blogproject/mondai1_3/forms.py
from django import forms

class QuestionForm(forms.Form):
    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    question_title = forms.CharField(label='質問タイトル')
    question_detail = forms.CharField(label='質問詳細', widget=forms.Textarea)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['name'].widget.attrs['placeholder'] = 'お名前を入力してください'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        
        self.fields['question_title'].widget.attrs['class'] = 'form-control'
        self.fields['question_title'].widget.attrs['placeholder'] = '質問タイトルを入力してください。'

        self.fields['question_detail'].widget.attrs['class'] = 'form-control'
        self.fields['question_detail'].widget.attrs['placeholder'] = '質問詳細を入力してください。'


blogproject/mondai1_3/views.py
from email.message import EmailMessage
from pyexpat.errors import messages
import sys
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView

from .forms import QuestionForm

# Create your views here.

class TopView(TemplateView):
    template_name = "mondai1_3/top.html"

class QuestionView(FormView):
    template_name = 'mondai1_3/question.html'
    form_class = QuestionForm
    success_url = reverse_lazy('mondai1_3:question')

    # test
    
    def dispatch(self, request, *args, **kwargs):
        # ← リクエスト毎に必ず通る
        print("stdout encoding:", sys.stdout.encoding)
        s = "test 波ダッシュ：\u301c / 全角チルダ：\uff5e / EM DASH：—"
        print(s)  # 環境により文字化け or 正常表示（UTF-8出力なら例外は出ない）
        """
        try:
            sys.stdout.reconfigure(encoding="shift_jis")
            print("FULLWIDTH TILDE: \uff5e")  # ← ここで UnicodeEncodeError になるはず
        finally:
            sys.stdout.reconfigure(encoding="utf-8")  # 元に戻す
        """
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['question_title']
        message = form.cleaned_data['question_detail']
        
        subject = 'お問い合わせ：{}'.format(title)
        message = '送信者名：{0}\nメールアドレス：{1}\nタイトル：{2}\nメッセージ：{3}'.format(name, email, title, message)
        
        from_email = 'admin@example.com'
        to_list = ['admin@example.com']
        
        message = EmailMessage(subject=subject, body=message,from_email=from_email, to=to_list)
        message.send()
        
        messages.success(self.request, 'お問い合わせは正常に送信されました')
        return super().form_valid(form)

blogproject/mondai1_3/templates/mondai1_3/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'mondai1:top' %}">Django's mondai1</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'mondai1:top' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">IT</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">HTML/CSS</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">LINUX</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">PYTHON I</a></li>
                </ul>
            </div>
        </div>
    </nav>

    {% block header %}{% endblock %}

    {% block contents %}{% endblock %}

    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="https://twitter.com">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.facebook.com/">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.co.jp/">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Django's mondai1</div>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

blogproject/mondai1_3/templates/mondai1_3/question.html
{% extends 'mondai1_3/base2.html' %}
{% load static %}

{% block title %}Django's mondai1 - 質問{% endblock %}

{% block header %}
    <header class="masthead" style="background-image: url('{% static "assets/img/contact-bg.jpg" %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="page-heading">
                        <h1>質問</h1>
                        <span class="subheading">質問を送信してください</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block contents %}
    <main class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">

                    {% if messages %}
                        <ul class="list-unstyled">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    <div class="my-5">
                        <form method="post">
                            {% csrf_token %}

                            {% for field in form %}
                                <div class="form-floating">
                                    <div class="form-group floating-label-form-group controls">
                                        {{ field.label_tag }}
                                        {{ field }}
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                            {% endfor %}

                            <br>
                            <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
        <hr>
    </main>
{% endblock %}

blogproject/mondai1_3/templates/mondai1_3/top.html
{% extends 'mondai1_2/base2.html' %}
{% load static %}

{% block title %}Django's mondai1{% endblock %}

{% block header %}
    <header class="masthead" style="background-image: url('{% static "assets/img/home-bg.jpg" %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Django's mondai1</h1>
                        <span class="subheading">Django 演習問題</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block contents %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {% for record in orderby_records %}
                    <div class="post-preview">
                        <a href="#">
                            <h2 class="post-title">
                                {{ record.title }}
                            </h2>
                            <h3 class="post-subtitle">
                                <span style="font-size: 14pt">
                                    {{ record.content|truncatechars:50 }}
                                </span>
                            </h3>
                        </a>
                        <p class="post-meta">
                            <a href="#">Django's mondai1</a>
                            {{ record.posted_at }}に投稿/カテゴリ：{{ record.category }}
                        </p>
                    </div>
                    <hr class="my-4" />
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}