blogproject/blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'

urlpatterns = [
    path('' , views.IndexView.as_view(), name='index'),
    path('blog-detail/<int:pk>/', views.BlogDetailView.as_view(), name='blog_detail'),
        # scienceカテゴリの一覧ページのURLパターン
    path(
        # scienceカテゴリの一覧ページのURLは「science-list/」
        'science-list/',
        # viewsモジュールのBlogDetailを実行
        views.ScienceView.as_view(),
        # URLパターンの名前を'science_list'にする
        name='science_list'
        ),
    # dailylifeカテゴリの一覧ページのURLパターン
    path(
        # dailylifeカテゴリの一覧ページのURLは「dailylife-list/」
        'dailylife-list/',
        # viewsモジュールのDailylifeViewを実行
        views.DailylifeView.as_view(),
        # URLパターンの名前を'dailylife_list'にする
        name='dailylife_list'
        ),
    # musicカテゴリの一覧ページのURLパターン
    path(
        # scienceカテゴリの一覧ページのURLは「music-list/」
        'music-list/',
        # viewsモジュールのMusicViewを実行
        views.MusicView.as_view(),
        # URLパターンの名前を'music_list'にする
        name='music_list'
        ),
        
    # 問い合わせページのURLパターン
    path(
        # 問い合わせページのURLは「contact/」
        'contact/',
        # viewsモジュールのContactViewを実行,
        views.ContactView.as_view(),
        # URLパターンの名前を'contact'にする
        name='contact'
    ),
]

blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path, include # , include追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include(('blogapp.urls', 'blogapp'), namespace='blogapp')),
    path('mondai1/', include('mondai1.urls')),
    path('mondai1_2/', include('mondai1_2.urls')),
    path('mondai1_3/', include('mondai1_3.urls')),
    path('mondai2/', include('mondai2.urls')),
    path('seisaku/', include(('seisaku.urls', 'seisaku'), namespace='seisaku')),  # 制作課題 
]

blogproject/seisaku/urls.py
from django.urls import path
from . import views

# アプリ名を登録
#   URLconfのURLパターンを逆引きできるように名前を登録する
app_name = 'seisaku'

# アプリのURLパターンを登録
#   urlpatternsのリストに記述する
urlpatterns = [
    # http(s)://ホスト名/以下のパスが''(無し)の場合
    # viewsモジュールのIndexViewを実行
    # URLパターン名は 'index'
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('post/<int:pk>/', views.PostView.as_view(), name='post'), 
    path('contact/', views.ContactView.as_view(), name='contact'),
]

blogproject/test1_project/test1_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test1/',include('test1_app.urls')),
]

blogproject/seisaku/models.py
from django.db import models

class BlogPost(models.Model):
    '''モデルクラス'''
    CATEGORY = (
        ('science', '科学のこと'),
        ('dailylife', '日常のこと'),
        ('music', '音楽のこと'),
    )

    title = models.CharField(verbose_name='タイトル', max_length=200)
    content = models.TextField(verbose_name='本文')
    posted_at = models.DateTimeField(verbose_name='投稿日時', auto_now_add=True)
    category = models.CharField(verbose_name='カテゴリ', max_length=50, choices=CATEGORY)

    def __str__(self):
        return self.title
    

blogproject/seisaku/forms.py
# seisaku/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    question_title = forms.CharField(label='件名')
    question_detail = forms.CharField(label='お問い合わせ内容', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'placeholder': 'お名前を入力してください',
            'class': 'form-control'
        })
        self.fields['email'].widget.attrs.update({
            'placeholder': 'メールアドレスを入力してください',
            'class': 'form-control'
        })
        self.fields['question_title'].widget.attrs.update({
            'placeholder': '件名を入力してください。',
            'class': 'form-control'
        })
        self.fields['question_detail'].widget.attrs.update({
            'placeholder': 'お問い合わせ内容を入力してください。',
            'class': 'form-control'
        })

blogproject/seisaku/views.py
from django.views.generic import FormView, ListView, DetailView, TemplateView
from django.urls import reverse_lazy
from django.contrib import messages
from django.core.mail import EmailMessage
from .models import BlogPost
from .forms import ContactForm

class IndexView(ListView):
    model = BlogPost
    template_name = 'seisaku/index.html'
    context_object_name = 'posts'
    ordering = ['-posted_at']
    paginate_by = 4

class AboutView(TemplateView):
    template_name = "seisaku/about.html"

class PostView(DetailView):
    model = BlogPost
    template_name = "seisaku/post.html"
    context_object_name = "post"

class ContactView(FormView):
    template_name = "seisaku/contact.html"
    form_class = ContactForm
    success_url = reverse_lazy('seisaku:contact')   # 送信後に同ページへリダイレクト

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['question_title']
        detail = form.cleaned_data['question_detail']

        subject = f'お問い合わせ：{title}'
        body = (
            f'送信者名：{name}\n'
            f'メールアドレス：{email}\n'
            f'タイトル：{title}\n'
            f'メッセージ：{detail}'
        )

        from_email = 'admin@example.com'    # settingsでDEFAULT_FROM_EMAILを使ってもOK
        to_list = ['admin@example.com']     # 宛先を必要に応じて設定

        EmailMessage(subject=subject, body=body, from_email=from_email, to=to_list).send()

        messages.success(self.request, 'お問い合わせは正常に送信されました')
        return super().form_valid(form)

blogproject/seisaku/templates/seisaku/about.html
{% extends "seisaku/base.html" %} {# ベーステンプレートを継承 #}
{% load static %}

{# ページタイトルの設定 #}
{% block title %}About{% endblock %}

{# <!DOCTYPE html> や <html> <head> <body> は base.html に移動したため削除 #}

    {# Page Header 部分を block header で囲む #}
    {% block header %}
    <header class="masthead" style="background-image: url('{% static "assets/img/about-bg.jpg" %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="page-heading">
                        <h1>About</h1>
                        <span class="subheading">このブログについて</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% endblock %}

    {# Main Content 部分を block contents で囲む #}
    {% block contents %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>このブログは Django の学習用サンプルサイトです。<br>
                   Clean Blog テンプレートを利用して制作しています。</p>
            </div>
        </div>
    </div>
    {% endblock %}

{# フッター部分および JS 読み込みは base.html に移動済み #}

blogproject/seisaku/templates/seisaku/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock%}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'seisaku:index' %}">Django's Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'seisaku:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'seisaku:about' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'seisaku:contact' %}">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        {% block header %}{% endblock %}

        <!-- Main Content-->
        {% block contents %}{% endblock %}
        
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="https://twitter.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://facebook.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://github.co.jp/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Django's Blog 2025</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

blogproject/seisaku/templates/seisaku/contact.html
{% extends "seisaku/base.html" %} {# ベーステンプレートを継承 #}
{% load static %}

{# ページタイトルの設定 #}
{% block title %}お問い合わせ{% endblock %}

{# <!DOCTYPE html> や <html> <head> <body> は base.html に移動したため削除 #}

{# Page Header 部分を block header で囲む #}
{% block header %}
<header class="masthead" style="background-image: url('{% static "assets/img/contact-bg.jpg" %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>お問い合わせ</h1>
                    <span class="subheading">お問い合わせはこちらから</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{# Main Content 部分を block contents で囲む #}
{% block contents %}
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">

        {% if messages %}
          <ul class="list-unstyled">
            {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}

        <div class="my-5">
          <form method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-floating">
              <div class="form-group floating-label-form-group controls">
                {{ field.label_tag }}
                {{ field }}
                <p class="help-block text-danger"></p>
              </div>
            </div>
            {% endfor %}
            <br>
            <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
          </form>
        </div>

      </div>
    </div>
  </div>
  <hr>
</main>
{% endblock %}
{# フッター部分および JS 読み込みは base.html に移動済み #}

blogproject/seisaku/templates/seisaku/index.html
{% extends "seisaku/base.html" %} {# ベーステンプレートを継承 #}
{% load static %}

{# ページタイトルの設定 #}
{% block title %}Django's Blog{% endblock %}

<!-- <!DOCTYPE html> を削除 -->
<!-- <html lang="ja"> を削除 -->
    <!-- <head>から</head> を削除(base.htmlに移動) -->

    <!-- <body> を削除 -->
        <!-- Navigation-->
        <!-- <nav>から</nav> を削除(base.htmlに移動) -->
        
        <!-- Page Header-->
        <!-- <header>から</header> をテンプレートタグで囲む block header  から endblock  -->
        {% block header %}
        <header class="masthead" style="background-image: url('{% static "assets/img/home-bg.jpg" %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Django's Blog</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}

        <!-- Main Content-->
        <!-- <div>から</div> をテンプレートタグで囲む block contents から endblock -->
        {% block contents %}

        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    {% for p in posts %}
                        <div class="post-preview">
                            <a href="{% url 'seisaku:post' pk=p.pk %}">
                                <h2 class="post-title">{{ p.title }}</h2>
                                {% if p.content %}
                                    <h3 class="post-subtitle">{{ p.content|truncatechars:80 }}</h3>
                                {% endif %}
                            </a>
                            <!-- + 投稿日時/カテゴリをモデルから表示 -->
                            <p class="post-meta">
                                投稿日時：{{ p.posted_at|date:"Y年n月j日" }}{% if p.category %} / {{ p.get_category_display }}{% endif %}
                            </p>
                        </div>
                        <!-- Divider-->
                        <hr class="my-4" />
                    {% empty %}
                        <p>投稿がありません。</p>
                    {% endfor %}

                    <!-- Pager-->
                    <div class="d-flex justify-content-between mb-4">
                        {% if page_obj.has_previous %}
                            <a class="btn btn-primary text-uppercase" href="?page={{ page_obj.previous_page_number }}">← 新しい記事へ</a>
                        {% else %}<span></span>{% endif %}
                        {% if page_obj.has_next %}
                            <a class="btn btn-primary text-uppercase" href="?page={{ page_obj.next_page_number }}">過去の記事へ →</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
        
        <!-- Footer-->
        <!-- <footer>から</footer> を削除(base.htmlに移動) -->

        <!-- Bootstrap core JS-->
        <!-- JS を base.html に移動 -->

blogproject/seisaku/templates/seisaku/post.html
{% extends "seisaku/base.html" %} {# ベーステンプレートを継承 #}
{% load static %}

{# ページタイトルの設定 #}
{% block title %}Django's Blog{% endblock %}
    <!-- <body> を削除 -->
        <!-- Navigation-->
        <!-- <nav>から</nav> を削除 -->
        
        <!-- Page Header-->
        <!-- <header>から</header> をテンプレートタグで囲む block header から endblock -->
        {% block header %}
        <header class="masthead" style="background-image: url('{% static "assets/img/post-bg.jpg" %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>{{ post.title }}</h1>
                            <span class="meta">
                                投稿日時：{{ post.posted_at|date:"Y年n月j日" }}
                                {% if post.category %} / {{ post.get_category_display }}{% endif %}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}

        <!-- Post Content-->
        {% block contents %}
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>{{ post.content|linebreaks }}</p>
                    </div>
                </div>
            </div>
        </article>
        <!-- 水平線を追加 -->
        <!-- <hr> -->
        {% endblock %}
        
        <!-- Footer-->
        <!-- <footer>以下はベーステンプレートを使用するので削除する -->